title: Image

columns:
  - width: 1/2
    sections:
      content:
        type: fields
        fields:
          caption:
            label: Caption
            type: textarea
            size: small
  - width: 1/2
    sections:
      meta:
        type: fields
        fields:
          alt:
            label: Texte alternatif
            type: text
