title: Page
preset: page
pages: false

fields:
  mybuilder:
    label: Page Builder
    type: builder
    columns: 1 # Optional. If set to 2 or more, the builder blocks will be placed in a grid.
    fieldsets:
      bodytext:
        name: Text
        label: Text — {{title}}
        preview:
          snippet: blocks/bodytext
        defaultView: preview 
        fields:
          title: 
            label: Section title
            type: text
          text:
            label: Text
            type: textarea
      imagesgallery:
        name: Image gallery
        label: Image gallery
        preview:
          snippet: blocks/imagesgallery
        defaultView: preview 
        fields:
          selectimages:
            label: Images 
            type: files
            query: page.images
      list:
        name: List
        label: List - {{title}} 
        preview:
          snippet: blocks/list
        fields:
          title: 
            label: Title of the section (if needed)
            type: text
          elementlist: # The Builder Field can even be nested!
            type: builder
            label: List elements
            columns: 1
            fieldsets:
              element:
                label: — {{title}} 
                fields:
                  title:
                    label: Title
                    type: text
                  startdate:
                    label: Start date
                    type: date
                  enddate:
                    label: End date
                    type: date
                    help: This field can be left empty if there is only one date for the event
                  subtitle:
                    label: Subtitle
                    type: text
                  image:
                    label: Image
                    type: files
                    mode: single
                  text:
                    label: Text
                    type: textarea

